import './globals.css'
import { Inter } from 'next/font/google'
import Header from "@/app/components/header";
import Footer from "@/app/components/footer";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
      <html lang="en">
      <body className={inter.className}>
      <div className="">
        <Header />
        <main className="mt-10 min-h-full">
          {children}
        </main>
        <Footer />
      </div>

      </body>
      </html>
  )
}
